site_name: ReadGo
site_description: A powerful Go code analysis tool that helps developers explore and understand Go codebases with ease
site_author: iamlongalong
repo_url: https://github.com/iamlongalong/readgo
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    primary: blue
    accent: blue
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
  - User Guide:
    - Basic Usage: user-guide/basic-usage.md
    - Configuration: user-guide/configuration.md
    - Examples: user-guide/examples.md
  - Architecture: ARCHITECTURE.md
  - API Reference:
    - Interfaces: api/interfaces.md
    - Types: api/types.md
    - Functions: api/functions.md
  - Contributing: CONTRIBUTING.md
  - Changelog: CHANGELOG.md

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true

plugins:
  - search
  - minify:
      minify_html: true 